# Generated by Django 2.0 on 2018-01-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.TextField(default='[]', null=True),
        ),
    ]
