# Generated by Django 2.0 on 2018-03-28 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
